### ISSUE TITLE
Redundant time info when not running

### ISSUE THREAD

**Issue by plopp37** [gregorriegler/gnome-shell-extension-egg-timer#1]
There should be only an icon with no time label when timer is not running to save space (and be more pleasing to the eye)...

**Comment by gregorriegler** [comment]
i like the idea, but how would you then present the time-slider feedback? i can imagine showing the time label as soon as you open the menu.

**Comment by plopp37** [comment]
that makes sense


Dne po 17. 8. 2020 19:46 uživatel Gregor Riegler <notifications@github.com>
napsal:

**Comment by gregorriegler** [comment]
i made the change. can you check if this works for you?
after that i would release it.

**Comment by plopp37** [comment]
It's great this way, thank you!

Gregor Riegler <notifications@github.com> napsal Út, 18. srp 2020 v 
11∶07:
